### ISSUE TITLE
pegging CPU at 100%

### ISSUE THREAD

**Issue by cmfatih** [strongloop/strong-supervisor#108]
The version `1.5.1` is pegging CPU at 100% randomly...

We run as `slr --control /app/runctl --no-profile --cluster cpu --log - --no-timestamp-workers --no-timestamp-supervisor`

**Comment by sam-github** [comment]
Which node version is this?

**Comment by cmfatih** [comment]
```json
{
  "arch": "x64",
  "platform": "linux",
  "release": "2.6.32-504.3.3.el6.x86_64",
  "versions": {
    "http_parser": "1.0",
    "node": "0.10.33",
    "v8": "3.14.5.9",
    "ares": "1.9.0-DEV",
    "uv": "0.10.29",
    "zlib": "1.2.3",
    "modules": "11",
    "openssl": "1.0.1j"
  }
}
```

**Comment by rmg** [comment]
@cmfatih your version of node is a little old, but that shouldn't be relevant to this.. What version of strong-supervisor were you running before that did not have this problem?

**Comment by cmfatih** [comment]
@rmg : Currently we are using `strong-supervisor@1.4.1` without any issue.

P.S.: Yes, little bit old because we don't jump on latest node releases due to previous experiences. (For example https://github.com/joyent/node/issues/7590)

**Comment by sam-github** [comment]
Is it a worker or the master? Can you tell from the logs whether its processes dieing, or busy looping in js?

**Comment by cmfatih** [comment]
@sam-github : It was master. I don't understand 2nd question but I have ;
```
21421 x  20   0 1334m 425m 7504 S  0.7  2.8   1:51.60 node
21437 x  20   0 1287m 375m 7504 S  1.0  2.5   1:54.80 node
21414 x  20   0 1274m 365m 7492 S  1.0  2.4   1:53.90 node
21401 x  20   0 1270m 359m 7504 R 29.2  2.4   1:49.60 node
21397 x  20   0 1263m 354m 7508 S  0.7  2.4   1:41.64 node
21404 x  20   0 1260m 351m 7528 S  0.3  2.4   1:40.71 node
21399 x  20   0 1248m 307m 7492 S  0.7  2.1   1:49.27 node
21411 x  20   0 1174m 262m 7492 S  0.3  1.8   1:41.03 node
21392 x  20   0  803m 195m 6948 R 101.0  1.3  24:24.18 node
```

We pinned `"strong-supervisor": "1.4.1"` and not moving forward for a while. So that's the only log I have for you.

BTW: We are using `"statsd-client": "0.1.x"` for monitoring. I might be related to UDP/cluster issue like I mentioned at previous comment.

**Comment by rmg** [comment]
Assuming the first column is the pid, and that your OS assigns them incrementally, I would guess that your master process is busy restarting crashed workers. Log output would be most helpful for debugging that.

**Comment by cmfatih** [comment]
We are using v2 and so far no issue. You folks can close this issue or I will do it later...
