### ISSUE TITLE
Disable creation of heapdump files

### ISSUE THREAD

**Issue by grimborg** [strongloop/strong-supervisor#148]
I'm using `slr` to launch my app How can I prevent `heapdump` files from being created?

**Comment by rmg** [comment]
@grimborg not sure what you mean, since they are generated on demand. Are they being triggered accidentally?

**Comment by grimborg** [comment]
@rmg thanks for your answer. Unless I'm missing something yes, they seem to be generated accidentally (probably on crash).

Here's how I'm launching my app:

    slr --cluster $num_procs \
        --pid $PID_FILE \
        --control $CONTROL_FILE \
        --log $LOG_FILE \
        --detach \
       myapp.js

I couldn't see any option to enable/disable heapdump files from being created, nor do I see anywhere in my code any request to create them (I don't even import any strongloop packages).

Am I missing something?

Thanks

**Comment by rmg** [comment]
Heap snapshots (a feature of supervisor) won't generally be created on crash. Do you mean core dumps (a feature of the OS), maybe? If so, that is something you will need to change in your OS.

Another possibility is that you are sending SIGUSR2 signals to the supervisor, which is how you tell strong-supervisor to re-open its log files (required for proper log rotation). If you are using that functionality, it looks like the `heapdump` module also listens for that signal by default. If that's the case, you can set `NODE_HEAPDUMP_OPTIONS=nosignal` in the strong-supervisor's environment to disable the signal trigger.

**Comment by rmg** [comment]
For reference: https://github.com/bnoordhuis/node-heapdump

**Comment by grimborg** [comment]
@rmg you guessed right, I'm sending SIGUSR2 to re-open the log files indeed. Adding `NODE_HEAPDUMP_OPTIONS=nosignal` fixes my problem. Thanks a lot for your help!

**Comment by rmg** [comment]
Glad that sorted it out for you :-)
