### ISSUE TITLE
SIGUSR2 triggers both log re-open and heapdump

### ISSUE THREAD

**Issue by rmg** [strongloop/strong-supervisor#150]
We should probably disable the heapdump handler since it is meant to be triggered via runctl instead.

See #148 for an example of it causing trouble/confusion.

**Comment by sam-github** [comment]
I agree.

**Comment by sam-github** [comment]
should be a simple matter of setting `NODE_HEAPDUMP_OPTIONS=nosignal` in env in supervisor, unconditionally.
