### ISSUE TITLE
Memory leak on nodeJs strongloop strong supervisor

### ISSUE THREAD

**Issue by vinojoy** [strongloop/strong-supervisor#171]
Our node supervisor is having memory leak and it's getting crashed. For below memory it takes around 2 weeks before we get OOM error.

// boot script
start() { 
cd ${APPDIR} 
mkdir -p ${LOGDIR} 
killall node 
sleep 5 
rm -rf ${APPDIR}/.tmp 
(slc run --no-profile -d --cluster <%= @clusters %> --log ${LOGDIR}/${APP_NAME}.log -p ${LOGDIR}/${APP_NAME}.pid ${APPDIR}/${APP} --port ***\* --max-old-space-size=8192) RETVAL=$?

//strongloop

/user/lig/node_modules/strongloop/nod_modules/strong-supervisor/bin/sl-run.js --no-profile --no-detach--cluster cpus --log/log

it runs on AWS m3.large 7.5 GB ram. There are 3 instances in cluster

Version of Express you are using : 4.13.3
Version of Node.js you are using : v0.10.39

Any suggestions are appreciated

**Comment by vinojoy** [comment]
more details

strongloop v5.0.1 (node v0.10.39)
├── strong-arc@1.8.3 (d95b140)
├── strong-build@2.0.6 (d008a3e)
├── strong-deploy@3.1.2 (be6180a)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.0.1 (b96f806)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.2 (1327018)
├─┬ strong-supervisor@3.3.0 (46b06b4)
│ └── strong-agent@2.0.2 (4ea7ee9)
├── generator-loopback@1.12.1 (a374136)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

**Comment by sam-github** [comment]
By OOM, you mean the kernel is determining there is not enough memory, and killing some process, probably node? If so, that is not necessarily a memory leak on supervisor's part, but more likely that you don't have enough memory. v8 uses memory very agressively, it can easily use all the aprox 1.5Gig max memory of each node process, of which you seem to have 4. That only amounts to 6G, and you say your instance has 7.5G, but I don't know what else is running.

Anyhow, OOM means that you don't have enough memory.

If you don't hit OOM, but still have a mem leak, you will see a gradual rise in mem usage by a node process (which is ok) and then finally that node process will self-abort on failure to allocate memory.

If this is happening, then its a mem leak, and we'd need to know which process, master or worker is leaking. If its master, its obviously supervisor, if its a worker... it is possible it is, but also possibly your express app. Best way to detemine would be to run without supervisor and see, or just replace supervisor (you don't actually appear to be using any of its features) with a single node instance, possible doing a cluster.fork() 3 times, and see if it still happens.

Without something that more clearly points to the supervisor (it happens with supervisor, and doesn't without), its not likely we'll be able to reproduce this, or do anything helpful for you.

**Comment by elankeeran** [comment]
@vinojoy any update on this issues?

**Comment by vinojoy** [comment]
We moved to PM2

Regards,
Vino Joy
