### ISSUE TITLE
run --path and --port and --addr no longer work

### ISSUE THREAD

**Issue by sam-github** [strongloop/strong-supervisor#76]
This is a problem for https://github.com/strongloop/strongloop/issues/179, because a non-default location for the socket can't be chosen, nor can a TCP port.

Generally, the options parsing needs to be cleaned up and `strong-cluster-control:loadOptions()` removed and moved into strong-supervisor.

**Comment by sam-github** [comment]
Verifiable once https://github.com/strongloop/strong-supervisor/pull/82 is merged and hits staging.

**Comment by cgole** [comment]
verified -
1. slc run --cluster 2
slc runctl - works
2. slc run --cluster 2 -C localhost:3020
slc runctl  - ECONNREFUSED
3. slc run --cluster 2 -C localhost:3020
slc runctl  -C localhost:3020 - works
4. slc run --cluster 2 --no-cluster
slc runctl  - ECONNREFUSED
