### ISSUE TITLE
pid:undefined worker:statsd in supervisor log output

### ISSUE THREAD

**Issue by sam-github** [strongloop/strong-supervisor#89]
Should NOT be there! Don't know why it is

```
% slc run --no-timestamp-supervisor --no-timestamp-workers --cluster=1 --metrics=log .
...
pid:undefined worker:statsd 1970-01-01T00:23:43.076Z statsd.timestamp_lag=0 (gauge)
```

there should no longer be a statsd child, maybe something is broken with the log messages?

**Comment by rmg** [comment]
The `pid:undefined` is because statsd is running in process and the fake child process object being given to the log transformer does not have a pid. Easy to fix.

The timestamps being wrong is a bug in strong-statsd, also easy to fix.

**Comment by cgole** [comment]
verified. pid:10022 worker:statsd 2015-02-09T20:05:21.000Z test1.Chandrikas-MacBook-Air.1.heap.total=88871463 (gauge)
pid:10022 worker:statsd 2015-02-09T20:05:21.000Z test1.Chandrikas-MacBook-Air.1.cpu.total=0.02542 (gauge)
pid:10022 worker:statsd 2015-02-09T20:05:21.000Z test1.Chandrikas-MacBook-Air.1.cpu.system=0.0223 (gauge)
pid:10022 worker:statsd 2015-02-09T20:05:21.000Z test1.Chandrikas-MacBook-Air.1.cpu.user=0.00313 (gauge)
pid:10022 worker:statsd 2015-02-09T20:05:21.000Z statsd.timestamp_lag=52 (gauge)

**Comment by rmg** [comment]
strong-supervisor@1.4.1 has been published with the `pid:undefined` part of the fix.

strong-statsd@2.0.2 is tagged and ready for release, fixing the timestamp part, but @sam-github will have to publish it.
