### ISSUE TITLE
When running in cluster mode, should be able to disable worker/pid tag prefix

### ISSUE THREAD

**Issue by dtabwhite** [strongloop/strong-supervisor#99]
Similar to how you can specify `--no-timestamp-workers` and `--no-timestamp-supervisor` it would be nice to be able to pass an option like `--no-tags` to be able to *not* get output prefixed like this for each log line:

`pid:<pid> worker:<worker>`

The reason I would like these not included by default is that I'm trying to use bunyan to log everything from the application in json.  These pid/worker prefixes prevent each line from being a valid json record.

**Comment by sam-github** [comment]
Without knowing more about your setup, where you are directing your logs, how you are processing them, its had to give very specific advice.

I'm not very excited about stripping pid/wid stamps from lines, the supervisor is the "kernel" of the strongloop process manager, strong-pm, and strong-pm requires the origin of log lines (in terms of which worker) to be identified. We'd probably accept a well-structured PR, but I'm not sure we'd implement this feature ourselves.

Btw, I'd expect the json consumer to be robust in the face of non-json output, to search for valid json and ignore non-json prefixes. I guess that isn't the case? Your consumer is never going to work with standard tools, like syslog, if it can't strip non-json prefixes from line-oriented log streams.

The best way to ensure pure-json log files, guaranteed, would be to have bunyan directly write the json to log itself, wouldn't it? Is that an option for you? I'm not sure where you are directing supervisor's log output.

**Comment by rmg** [comment]
The internal module used for this does have support for producing JSON output, which would probably be a nicer solution, but that is currently not exposed by supervisor.

I would like to see support for JSON input added to [strong-log-transformer](https://github.com/strongloop/strong-log-transformer) before exposing the JSON format via supervisor. That way you can get proper JSON augmentation instead of ugly nested JSON with more escape characters than you can shake a stick at.

**Comment by dtabwhite** [comment]
My specific use case is running running my apps with runit -> slr. So I'm not using strong-pm at this time.  Within the application that slr manages, I'm using bunyan for all logging and simply logging to a process.stdout stream which is fed to runit svlogd.  So for a given app I get all my supervisor and worker logs collected and logged together.  This is convenient in that I can go to a single log file for my app (something like `/var/log/<name>/current`) and see all the logs for all the workers (and supervisor) for the app.  If it wasn't for the fact that I'm logging with bunyan and want all those log lines to be *just* json I would love the worker/pid prefixing.

Now I could have bunyan writing to file streams instead of process.stdout but then I need to deal with those separate workers writing to the same log files and/or directing each worker to it's own log file.  While possible, it would be nice if I at least had the option to turn on/off the worker/pid prefixes.

Regarding exposing json support from strong-log-transformer, that may be nice as well, but there may be cases where I'd like to precisely control the structure of the json being logged.  I can do this with bunyan with custom serializers, etc.  In addition I can also *include* the worker/pid for a process by pulling this information in myself at log time from the cluster module and including it myself as separate fields in the json structure that bunyan will log.

**Comment by rmg** [comment]
@dtabwhite would you be interested in submitting a PR to add a `--raw-logs` option that disables all the log augmentation features?

**Comment by dtabwhite** [comment]
@rmg Sure I can do that.  I already had one nearly ready that added `--no-tags` but I can change it up to be `--raw-logs` if you like that disables all the prefixing and is false by default to preserve the existing behavior.  btw - The reason I did it initially as `--no-tags` was to allow the user to selectively include/exclude the tags and/or timestamps separately.  Either way though is fine for me.

**Comment by rmg** [comment]
@dtabwhite I'm worried about a proliferation of flags if/when additional prefixes get added. I figured raw as a complete opt-out would be more clear and easier to maintain.

On the other hand, `--raw-logs` is an annoying negative option.. @sam-github any suggestions/opinions on what to call the option?

**Comment by sam-github** [comment]
- `--log-decoration` (the default)
- `--no-log-decoration` 

or some such variant, maybe? using `--no-` is already a pattern in the options, see `--no-control`, so that would make a better negative

@dtabwhite thanks for the details on your setup
